//package com.example.diagramtest;
//
//import org.vaadin.diagrambuilder.DiagramBuilder;
//
//import com.vaadin.annotations.AutoGenerated;
//import com.vaadin.ui.AbsoluteLayout;
//import com.vaadin.ui.Component;
//import com.vaadin.ui.CustomComponent;
//import com.vaadin.ui.Notification;
//
//public class myDBuilderComposite extends CustomComponent {
//
//	DiagramBuilder dBuilder;
//	@AutoGenerated
////	private AbsoluteLayout mainLayout;
//
//	/**
//	 * The constructor should first build the main layout, set the
//	 * composition root and then do any custom initialization.
//	 *
//	 * The constructor will not be automatically regenerated by the
//	 * visual editor.
//	 */
//	public myDBuilderComposite() {
//		// Just a single component in this composition
//		dBuilder = new DiagramBuilder();
//		dBuilder.addListener((Listener) this);
////        layout.addComponent(button);
//        
//        setCompositionRoot(dBuilder);//		buildMainLayout();
////		setCompositionRoot(mainLayout);
//
//		// TODO add user code here
//	}
//
//    // The listener method implementation
//    public void componentEvent(Event event) {
//        // Act according to the source of the event
//        if (event.getSource() == dBuilder && event.getClass() == Component.Event.class)
//        	// do something
////            getWindow().showNotification("Click!");
//
//        // Display source component and event class names
//       	Notification.show("Event from " + event.getSource().getClass().getName()
//                + ": " + event.getClass().getName());
//    }
//    
//    
//	@AutoGenerated
//	private void buildMainLayout() {
//		// the main layout and components will be created here
////		mainLayout = new AbsoluteLayout();
//	}
//
//}
